name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  compile:
    name: Compile api-test-suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/ntiwari-z/api-test-suite:sha256-5cada4568e7c77718b8cbc56004f0da0c852a1d5af20e09cfabb18549a5f592c.sig
            options: -v ${{ github.workspace }}:/tests
            run: |
                dotnet build
                dotnet test
